create table public.attendance_headers (
  id uuid not null default extensions.uuid_generate_v4 (),
  user_id uuid not null,
  employee_id text not null,
  branch text not null,
  year integer not null,
  month integer not null,
  workplace text null,
  status character varying(2) not null default '00'::character varying,
  total_working_days integer null,
  holiday_working_days integer null,
  absence_days integer null,
  total_working_hours numeric(5, 2) null,
  late_early_hours numeric(3, 1) null,
  paid_leave_days numeric(3, 1) null,
  remarks text null,
  submitted_at timestamp with time zone null,
  created_by uuid not null,
  created_at timestamp with time zone null default now(),
  updated_by uuid not null,
  updated_at timestamp with time zone null default now(),
  constraint attendance_headers_pkey primary key (id),
  constraint attendance_headers_user_id_year_month_key unique (user_id, year, month),
  constraint attendance_headers_created_by_fkey foreign KEY (created_by) references users (id),
  constraint attendance_headers_updated_by_fkey foreign KEY (updated_by) references users (id),
  constraint attendance_headers_user_id_fkey foreign KEY (user_id) references users (id)
) TABLESPACE pg_default;